version: "3.8"

services:
  scam_master_zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: scam_master_zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    ports:
      - "${SCAM_MASTER_ZOOKEEPER_PORT:-2181}:2181"

  scam_master_kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: scam_master_kafka
    restart: always
    depends_on:
      - scam_master_zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://scam_master_kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: scam_master_zookeeper:2181
    ports:
      - "${SCAM_MASTER_KAFKA_PORT:-29092}:29092"

  scam_master:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: scam_master
    restart: always
    depends_on:
      - scam_master_kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: scam_master_kafka:9092
    volumes:
      - "${SCAM_MASTER_LOG_DIR:-./logs}:/app/logs"
    ports:
      - "${SCAM_MASTER_PORT:-5000}:80"  
      - "${SCAM_MASTER_VNC_PORT:-5900}:5900"
